steps:
  # Bước 1: Build image từ Dockerfile và gắn thẻ nó với registry của Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      '--build-arg',
      'TELEGRAM_TOKEN',
      '--build-arg',
      'TELEGRAM_CHAT_ID',
      "-t", 
      "gcr.io/${PROJECT_ID}/blockchain-newsfeed-server", 
      "."
    ]
    secretEnv: [
      'TELEGRAM_TOKEN',
      'TELEGRAM_CHAT_ID',
    ]

  # Bước 2: Push image vừa build lên GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/blockchain-newsfeed-server"]

  # Bước 3: Deploy ứng dụng lên Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "blockchain-newsfeed-server-2",  # Tên service trên Cloud Run
        "--image",
        "gcr.io/${PROJECT_ID}/blockchain-newsfeed-server",  # Đường dẫn image vừa push lên GCR
        "--region",
        "us-central1",
        "--platform",
        "managed",  # Sử dụng nền tảng Cloud Run managed
        "--allow-unauthenticated",  # Cho phép truy cập không xác thực
      ]

# Định nghĩa các image đầu ra
images:
  - "gcr.io/${PROJECT_ID}/blockchain-newsfeed-server"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/BLOCKCHAIN_NEWSFEED_SERVER_TELEGRAM_TOKEN/versions/latest
      env: TELEGRAM_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/BLOCKCHAIN_NEWSFEED_SERVER_TELEGRAM_CHAT_ID/versions/latest
      env: TELEGRAM_CHAT_ID
      